/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IBorrowerOperationsInterface extends ethers.utils.Interface {
  functions: {
    "BORROWING_FEE_FLOOR()": FunctionFragment;
    "addColl(address,address)": FunctionFragment;
    "adjustNueTrove(uint256,uint256,uint256,bool,address,address)": FunctionFragment;
    "adjustTrove(uint256,uint256,uint256,bool,address,address)": FunctionFragment;
    "claimCollateral()": FunctionFragment;
    "closeNueTrove()": FunctionFragment;
    "closeTrove()": FunctionFragment;
    "getCompositeDebt(uint256)": FunctionFragment;
    "moveETHGainToTrove(address,address,address)": FunctionFragment;
    "openNueTrove(uint256,uint256,address,address)": FunctionFragment;
    "openTrove(uint256,uint256,address,address)": FunctionFragment;
    "repayZUSD(uint256,address,address)": FunctionFragment;
    "setAddresses(address,address,address,address,address,address,address,address,address,address,address,address)": FunctionFragment;
    "withdrawColl(uint256,address,address)": FunctionFragment;
    "withdrawZUSD(uint256,uint256,address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "BORROWING_FEE_FLOOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addColl",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "adjustNueTrove",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "adjustTrove",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimCollateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "closeNueTrove",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "closeTrove",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCompositeDebt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "moveETHGainToTrove",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "openNueTrove",
    values: [BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "openTrove",
    values: [BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "repayZUSD",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddresses",
    values: [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawColl",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawZUSD",
    values: [BigNumberish, BigNumberish, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "BORROWING_FEE_FLOOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addColl", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "adjustNueTrove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adjustTrove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeNueTrove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "closeTrove", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCompositeDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "moveETHGainToTrove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openNueTrove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "openTrove", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "repayZUSD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawColl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawZUSD",
    data: BytesLike
  ): Result;

  events: {
    "ActivePoolAddressChanged(address)": EventFragment;
    "CollSurplusPoolAddressChanged(address)": EventFragment;
    "DefaultPoolAddressChanged(address)": EventFragment;
    "FeeDistributorAddressChanged(address)": EventFragment;
    "GasPoolAddressChanged(address)": EventFragment;
    "PriceFeedAddressChanged(address)": EventFragment;
    "SortedTrovesAddressChanged(address)": EventFragment;
    "StabilityPoolAddressChanged(address)": EventFragment;
    "TroveCreated(address,uint256)": EventFragment;
    "TroveManagerAddressChanged(address)": EventFragment;
    "TroveUpdated(address,uint256,uint256,uint256,uint8)": EventFragment;
    "ZEROStakingAddressChanged(address)": EventFragment;
    "ZUSDBorrowingFeePaid(address,uint256)": EventFragment;
    "ZUSDTokenAddressChanged(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ActivePoolAddressChanged"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "CollSurplusPoolAddressChanged"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DefaultPoolAddressChanged"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "FeeDistributorAddressChanged"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GasPoolAddressChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PriceFeedAddressChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SortedTrovesAddressChanged"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "StabilityPoolAddressChanged"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TroveCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TroveManagerAddressChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TroveUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ZEROStakingAddressChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ZUSDBorrowingFeePaid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ZUSDTokenAddressChanged"): EventFragment;
}

export type ActivePoolAddressChangedEvent = TypedEvent<
  [string] & { _activePoolAddress: string }
>;

export type CollSurplusPoolAddressChangedEvent = TypedEvent<
  [string] & { _collSurplusPoolAddress: string }
>;

export type DefaultPoolAddressChangedEvent = TypedEvent<
  [string] & { _defaultPoolAddress: string }
>;

export type FeeDistributorAddressChangedEvent = TypedEvent<
  [string] & { _feeDistributorAddress: string }
>;

export type GasPoolAddressChangedEvent = TypedEvent<
  [string] & { _gasPoolAddress: string }
>;

export type PriceFeedAddressChangedEvent = TypedEvent<
  [string] & { _newPriceFeedAddress: string }
>;

export type SortedTrovesAddressChangedEvent = TypedEvent<
  [string] & { _sortedTrovesAddress: string }
>;

export type StabilityPoolAddressChangedEvent = TypedEvent<
  [string] & { _stabilityPoolAddress: string }
>;

export type TroveCreatedEvent = TypedEvent<
  [string, BigNumber] & { _borrower: string; arrayIndex: BigNumber }
>;

export type TroveManagerAddressChangedEvent = TypedEvent<
  [string] & { _newTroveManagerAddress: string }
>;

export type TroveUpdatedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, number] & {
    _borrower: string;
    _debt: BigNumber;
    _coll: BigNumber;
    stake: BigNumber;
    operation: number;
  }
>;

export type ZEROStakingAddressChangedEvent = TypedEvent<
  [string] & { _zeroStakingAddress: string }
>;

export type ZUSDBorrowingFeePaidEvent = TypedEvent<
  [string, BigNumber] & { _borrower: string; _ZUSDFee: BigNumber }
>;

export type ZUSDTokenAddressChangedEvent = TypedEvent<
  [string] & { _zusdTokenAddress: string }
>;

export class IBorrowerOperations extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IBorrowerOperationsInterface;

  functions: {
    BORROWING_FEE_FLOOR(overrides?: CallOverrides): Promise<[BigNumber]>;

    addColl(
      _upperHint: string,
      _lowerHint: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    adjustNueTrove(
      _maxFee: BigNumberish,
      _collWithdrawal: BigNumberish,
      _debtChange: BigNumberish,
      isDebtIncrease: boolean,
      _upperHint: string,
      _lowerHint: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    adjustTrove(
      _maxFee: BigNumberish,
      _collWithdrawal: BigNumberish,
      _debtChange: BigNumberish,
      isDebtIncrease: boolean,
      _upperHint: string,
      _lowerHint: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimCollateral(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    closeNueTrove(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    closeTrove(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getCompositeDebt(
      _debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    moveETHGainToTrove(
      _user: string,
      _upperHint: string,
      _lowerHint: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    openNueTrove(
      _maxFee: BigNumberish,
      _ZUSDAmount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    openTrove(
      _maxFee: BigNumberish,
      _ZUSDAmount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    repayZUSD(
      _amount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAddresses(
      _feeDistributorAddress: string,
      _liquityBaseParamsAddress: string,
      _troveManagerAddress: string,
      _activePoolAddress: string,
      _defaultPoolAddress: string,
      _stabilityPoolAddress: string,
      _gasPoolAddress: string,
      _collSurplusPoolAddress: string,
      _priceFeedAddress: string,
      _sortedTrovesAddress: string,
      _zusdTokenAddress: string,
      _zeroStakingAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawColl(
      _amount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawZUSD(
      _maxFee: BigNumberish,
      _amount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  BORROWING_FEE_FLOOR(overrides?: CallOverrides): Promise<BigNumber>;

  addColl(
    _upperHint: string,
    _lowerHint: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  adjustNueTrove(
    _maxFee: BigNumberish,
    _collWithdrawal: BigNumberish,
    _debtChange: BigNumberish,
    isDebtIncrease: boolean,
    _upperHint: string,
    _lowerHint: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  adjustTrove(
    _maxFee: BigNumberish,
    _collWithdrawal: BigNumberish,
    _debtChange: BigNumberish,
    isDebtIncrease: boolean,
    _upperHint: string,
    _lowerHint: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimCollateral(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  closeNueTrove(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  closeTrove(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getCompositeDebt(
    _debt: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  moveETHGainToTrove(
    _user: string,
    _upperHint: string,
    _lowerHint: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  openNueTrove(
    _maxFee: BigNumberish,
    _ZUSDAmount: BigNumberish,
    _upperHint: string,
    _lowerHint: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  openTrove(
    _maxFee: BigNumberish,
    _ZUSDAmount: BigNumberish,
    _upperHint: string,
    _lowerHint: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  repayZUSD(
    _amount: BigNumberish,
    _upperHint: string,
    _lowerHint: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAddresses(
    _feeDistributorAddress: string,
    _liquityBaseParamsAddress: string,
    _troveManagerAddress: string,
    _activePoolAddress: string,
    _defaultPoolAddress: string,
    _stabilityPoolAddress: string,
    _gasPoolAddress: string,
    _collSurplusPoolAddress: string,
    _priceFeedAddress: string,
    _sortedTrovesAddress: string,
    _zusdTokenAddress: string,
    _zeroStakingAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawColl(
    _amount: BigNumberish,
    _upperHint: string,
    _lowerHint: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawZUSD(
    _maxFee: BigNumberish,
    _amount: BigNumberish,
    _upperHint: string,
    _lowerHint: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    BORROWING_FEE_FLOOR(overrides?: CallOverrides): Promise<BigNumber>;

    addColl(
      _upperHint: string,
      _lowerHint: string,
      overrides?: CallOverrides
    ): Promise<void>;

    adjustNueTrove(
      _maxFee: BigNumberish,
      _collWithdrawal: BigNumberish,
      _debtChange: BigNumberish,
      isDebtIncrease: boolean,
      _upperHint: string,
      _lowerHint: string,
      overrides?: CallOverrides
    ): Promise<void>;

    adjustTrove(
      _maxFee: BigNumberish,
      _collWithdrawal: BigNumberish,
      _debtChange: BigNumberish,
      isDebtIncrease: boolean,
      _upperHint: string,
      _lowerHint: string,
      overrides?: CallOverrides
    ): Promise<void>;

    claimCollateral(overrides?: CallOverrides): Promise<void>;

    closeNueTrove(overrides?: CallOverrides): Promise<void>;

    closeTrove(overrides?: CallOverrides): Promise<void>;

    getCompositeDebt(
      _debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    moveETHGainToTrove(
      _user: string,
      _upperHint: string,
      _lowerHint: string,
      overrides?: CallOverrides
    ): Promise<void>;

    openNueTrove(
      _maxFee: BigNumberish,
      _ZUSDAmount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: CallOverrides
    ): Promise<void>;

    openTrove(
      _maxFee: BigNumberish,
      _ZUSDAmount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: CallOverrides
    ): Promise<void>;

    repayZUSD(
      _amount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setAddresses(
      _feeDistributorAddress: string,
      _liquityBaseParamsAddress: string,
      _troveManagerAddress: string,
      _activePoolAddress: string,
      _defaultPoolAddress: string,
      _stabilityPoolAddress: string,
      _gasPoolAddress: string,
      _collSurplusPoolAddress: string,
      _priceFeedAddress: string,
      _sortedTrovesAddress: string,
      _zusdTokenAddress: string,
      _zeroStakingAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawColl(
      _amount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawZUSD(
      _maxFee: BigNumberish,
      _amount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ActivePoolAddressChanged(address)"(
      _activePoolAddress?: null
    ): TypedEventFilter<[string], { _activePoolAddress: string }>;

    ActivePoolAddressChanged(
      _activePoolAddress?: null
    ): TypedEventFilter<[string], { _activePoolAddress: string }>;

    "CollSurplusPoolAddressChanged(address)"(
      _collSurplusPoolAddress?: null
    ): TypedEventFilter<[string], { _collSurplusPoolAddress: string }>;

    CollSurplusPoolAddressChanged(
      _collSurplusPoolAddress?: null
    ): TypedEventFilter<[string], { _collSurplusPoolAddress: string }>;

    "DefaultPoolAddressChanged(address)"(
      _defaultPoolAddress?: null
    ): TypedEventFilter<[string], { _defaultPoolAddress: string }>;

    DefaultPoolAddressChanged(
      _defaultPoolAddress?: null
    ): TypedEventFilter<[string], { _defaultPoolAddress: string }>;

    "FeeDistributorAddressChanged(address)"(
      _feeDistributorAddress?: null
    ): TypedEventFilter<[string], { _feeDistributorAddress: string }>;

    FeeDistributorAddressChanged(
      _feeDistributorAddress?: null
    ): TypedEventFilter<[string], { _feeDistributorAddress: string }>;

    "GasPoolAddressChanged(address)"(
      _gasPoolAddress?: null
    ): TypedEventFilter<[string], { _gasPoolAddress: string }>;

    GasPoolAddressChanged(
      _gasPoolAddress?: null
    ): TypedEventFilter<[string], { _gasPoolAddress: string }>;

    "PriceFeedAddressChanged(address)"(
      _newPriceFeedAddress?: null
    ): TypedEventFilter<[string], { _newPriceFeedAddress: string }>;

    PriceFeedAddressChanged(
      _newPriceFeedAddress?: null
    ): TypedEventFilter<[string], { _newPriceFeedAddress: string }>;

    "SortedTrovesAddressChanged(address)"(
      _sortedTrovesAddress?: null
    ): TypedEventFilter<[string], { _sortedTrovesAddress: string }>;

    SortedTrovesAddressChanged(
      _sortedTrovesAddress?: null
    ): TypedEventFilter<[string], { _sortedTrovesAddress: string }>;

    "StabilityPoolAddressChanged(address)"(
      _stabilityPoolAddress?: null
    ): TypedEventFilter<[string], { _stabilityPoolAddress: string }>;

    StabilityPoolAddressChanged(
      _stabilityPoolAddress?: null
    ): TypedEventFilter<[string], { _stabilityPoolAddress: string }>;

    "TroveCreated(address,uint256)"(
      _borrower?: string | null,
      arrayIndex?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { _borrower: string; arrayIndex: BigNumber }
    >;

    TroveCreated(
      _borrower?: string | null,
      arrayIndex?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { _borrower: string; arrayIndex: BigNumber }
    >;

    "TroveManagerAddressChanged(address)"(
      _newTroveManagerAddress?: null
    ): TypedEventFilter<[string], { _newTroveManagerAddress: string }>;

    TroveManagerAddressChanged(
      _newTroveManagerAddress?: null
    ): TypedEventFilter<[string], { _newTroveManagerAddress: string }>;

    "TroveUpdated(address,uint256,uint256,uint256,uint8)"(
      _borrower?: string | null,
      _debt?: null,
      _coll?: null,
      stake?: null,
      operation?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber, number],
      {
        _borrower: string;
        _debt: BigNumber;
        _coll: BigNumber;
        stake: BigNumber;
        operation: number;
      }
    >;

    TroveUpdated(
      _borrower?: string | null,
      _debt?: null,
      _coll?: null,
      stake?: null,
      operation?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber, number],
      {
        _borrower: string;
        _debt: BigNumber;
        _coll: BigNumber;
        stake: BigNumber;
        operation: number;
      }
    >;

    "ZEROStakingAddressChanged(address)"(
      _zeroStakingAddress?: null
    ): TypedEventFilter<[string], { _zeroStakingAddress: string }>;

    ZEROStakingAddressChanged(
      _zeroStakingAddress?: null
    ): TypedEventFilter<[string], { _zeroStakingAddress: string }>;

    "ZUSDBorrowingFeePaid(address,uint256)"(
      _borrower?: string | null,
      _ZUSDFee?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { _borrower: string; _ZUSDFee: BigNumber }
    >;

    ZUSDBorrowingFeePaid(
      _borrower?: string | null,
      _ZUSDFee?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { _borrower: string; _ZUSDFee: BigNumber }
    >;

    "ZUSDTokenAddressChanged(address)"(
      _zusdTokenAddress?: null
    ): TypedEventFilter<[string], { _zusdTokenAddress: string }>;

    ZUSDTokenAddressChanged(
      _zusdTokenAddress?: null
    ): TypedEventFilter<[string], { _zusdTokenAddress: string }>;
  };

  estimateGas: {
    BORROWING_FEE_FLOOR(overrides?: CallOverrides): Promise<BigNumber>;

    addColl(
      _upperHint: string,
      _lowerHint: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    adjustNueTrove(
      _maxFee: BigNumberish,
      _collWithdrawal: BigNumberish,
      _debtChange: BigNumberish,
      isDebtIncrease: boolean,
      _upperHint: string,
      _lowerHint: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    adjustTrove(
      _maxFee: BigNumberish,
      _collWithdrawal: BigNumberish,
      _debtChange: BigNumberish,
      isDebtIncrease: boolean,
      _upperHint: string,
      _lowerHint: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimCollateral(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    closeNueTrove(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    closeTrove(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getCompositeDebt(
      _debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    moveETHGainToTrove(
      _user: string,
      _upperHint: string,
      _lowerHint: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    openNueTrove(
      _maxFee: BigNumberish,
      _ZUSDAmount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    openTrove(
      _maxFee: BigNumberish,
      _ZUSDAmount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    repayZUSD(
      _amount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAddresses(
      _feeDistributorAddress: string,
      _liquityBaseParamsAddress: string,
      _troveManagerAddress: string,
      _activePoolAddress: string,
      _defaultPoolAddress: string,
      _stabilityPoolAddress: string,
      _gasPoolAddress: string,
      _collSurplusPoolAddress: string,
      _priceFeedAddress: string,
      _sortedTrovesAddress: string,
      _zusdTokenAddress: string,
      _zeroStakingAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawColl(
      _amount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawZUSD(
      _maxFee: BigNumberish,
      _amount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BORROWING_FEE_FLOOR(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addColl(
      _upperHint: string,
      _lowerHint: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    adjustNueTrove(
      _maxFee: BigNumberish,
      _collWithdrawal: BigNumberish,
      _debtChange: BigNumberish,
      isDebtIncrease: boolean,
      _upperHint: string,
      _lowerHint: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    adjustTrove(
      _maxFee: BigNumberish,
      _collWithdrawal: BigNumberish,
      _debtChange: BigNumberish,
      isDebtIncrease: boolean,
      _upperHint: string,
      _lowerHint: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimCollateral(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    closeNueTrove(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    closeTrove(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getCompositeDebt(
      _debt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    moveETHGainToTrove(
      _user: string,
      _upperHint: string,
      _lowerHint: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    openNueTrove(
      _maxFee: BigNumberish,
      _ZUSDAmount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    openTrove(
      _maxFee: BigNumberish,
      _ZUSDAmount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    repayZUSD(
      _amount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAddresses(
      _feeDistributorAddress: string,
      _liquityBaseParamsAddress: string,
      _troveManagerAddress: string,
      _activePoolAddress: string,
      _defaultPoolAddress: string,
      _stabilityPoolAddress: string,
      _gasPoolAddress: string,
      _collSurplusPoolAddress: string,
      _priceFeedAddress: string,
      _sortedTrovesAddress: string,
      _zusdTokenAddress: string,
      _zeroStakingAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawColl(
      _amount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawZUSD(
      _maxFee: BigNumberish,
      _amount: BigNumberish,
      _upperHint: string,
      _lowerHint: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
