/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ILiquityBaseParamsInterface extends ethers.utils.Interface {
  functions: {
    "BORROWING_FEE_FLOOR()": FunctionFragment;
    "CCR()": FunctionFragment;
    "MAX_BORROWING_FEE()": FunctionFragment;
    "MCR()": FunctionFragment;
    "PERCENT_DIVISOR()": FunctionFragment;
    "REDEMPTION_FEE_FLOOR()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "BORROWING_FEE_FLOOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "CCR", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_BORROWING_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MCR", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PERCENT_DIVISOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REDEMPTION_FEE_FLOOR",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BORROWING_FEE_FLOOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "CCR", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_BORROWING_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MCR", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PERCENT_DIVISOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REDEMPTION_FEE_FLOOR",
    data: BytesLike
  ): Result;

  events: {};
}

export class ILiquityBaseParams extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ILiquityBaseParamsInterface;

  functions: {
    BORROWING_FEE_FLOOR(overrides?: CallOverrides): Promise<[BigNumber]>;

    CCR(overrides?: CallOverrides): Promise<[BigNumber]>;

    MAX_BORROWING_FEE(overrides?: CallOverrides): Promise<[BigNumber]>;

    MCR(overrides?: CallOverrides): Promise<[BigNumber]>;

    PERCENT_DIVISOR(overrides?: CallOverrides): Promise<[BigNumber]>;

    REDEMPTION_FEE_FLOOR(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  BORROWING_FEE_FLOOR(overrides?: CallOverrides): Promise<BigNumber>;

  CCR(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_BORROWING_FEE(overrides?: CallOverrides): Promise<BigNumber>;

  MCR(overrides?: CallOverrides): Promise<BigNumber>;

  PERCENT_DIVISOR(overrides?: CallOverrides): Promise<BigNumber>;

  REDEMPTION_FEE_FLOOR(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    BORROWING_FEE_FLOOR(overrides?: CallOverrides): Promise<BigNumber>;

    CCR(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_BORROWING_FEE(overrides?: CallOverrides): Promise<BigNumber>;

    MCR(overrides?: CallOverrides): Promise<BigNumber>;

    PERCENT_DIVISOR(overrides?: CallOverrides): Promise<BigNumber>;

    REDEMPTION_FEE_FLOOR(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    BORROWING_FEE_FLOOR(overrides?: CallOverrides): Promise<BigNumber>;

    CCR(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_BORROWING_FEE(overrides?: CallOverrides): Promise<BigNumber>;

    MCR(overrides?: CallOverrides): Promise<BigNumber>;

    PERCENT_DIVISOR(overrides?: CallOverrides): Promise<BigNumber>;

    REDEMPTION_FEE_FLOOR(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    BORROWING_FEE_FLOOR(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    CCR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MAX_BORROWING_FEE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MCR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PERCENT_DIVISOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    REDEMPTION_FEE_FLOOR(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
