/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TroveStatisticsLibInterface extends ethers.utils.Interface {
  functions: {
    "calculateBorrowingFee(address,uint256)": FunctionFragment;
    "getEntireDebtAndColl(address,address)": FunctionFragment;
    "getNominalICR(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "calculateBorrowingFee",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntireDebtAndColl",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getNominalICR",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateBorrowingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntireDebtAndColl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNominalICR",
    data: BytesLike
  ): Result;

  events: {};
}

export class TroveStatisticsLib extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TroveStatisticsLibInterface;

  functions: {
    calculateBorrowingFee(
      troveManagerContractAddress: string,
      _ZUSDDebt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { borrowingFee: BigNumber }>;

    getEntireDebtAndColl(
      troveManagerContractAddress: string,
      _borrower: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        debt: BigNumber;
        coll: BigNumber;
        pendingZUSDDebtReward: BigNumber;
        pendingRBTCReward: BigNumber;
      }
    >;

    getNominalICR(
      troveManagerContractAddress: string,
      _borrower: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { collateralRatio: BigNumber }>;
  };

  calculateBorrowingFee(
    troveManagerContractAddress: string,
    _ZUSDDebt: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getEntireDebtAndColl(
    troveManagerContractAddress: string,
    _borrower: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber] & {
      debt: BigNumber;
      coll: BigNumber;
      pendingZUSDDebtReward: BigNumber;
      pendingRBTCReward: BigNumber;
    }
  >;

  getNominalICR(
    troveManagerContractAddress: string,
    _borrower: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    calculateBorrowingFee(
      troveManagerContractAddress: string,
      _ZUSDDebt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEntireDebtAndColl(
      troveManagerContractAddress: string,
      _borrower: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        debt: BigNumber;
        coll: BigNumber;
        pendingZUSDDebtReward: BigNumber;
        pendingRBTCReward: BigNumber;
      }
    >;

    getNominalICR(
      troveManagerContractAddress: string,
      _borrower: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    calculateBorrowingFee(
      troveManagerContractAddress: string,
      _ZUSDDebt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEntireDebtAndColl(
      troveManagerContractAddress: string,
      _borrower: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNominalICR(
      troveManagerContractAddress: string,
      _borrower: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    calculateBorrowingFee(
      troveManagerContractAddress: string,
      _ZUSDDebt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEntireDebtAndColl(
      troveManagerContractAddress: string,
      _borrower: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNominalICR(
      troveManagerContractAddress: string,
      _borrower: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
