/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IExternalPriceFeed,
  IExternalPriceFeedInterface,
} from "../IExternalPriceFeed";

const _abi = [
  {
    inputs: [],
    name: "latestAnswer",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IExternalPriceFeed__factory {
  static readonly abi = _abi;
  static createInterface(): IExternalPriceFeedInterface {
    return new utils.Interface(_abi) as IExternalPriceFeedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IExternalPriceFeed {
    return new Contract(address, _abi, signerOrProvider) as IExternalPriceFeed;
  }
}
